# Generated by Django 4.2.1 on 2023-05-09 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escuela', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('FechaDeNacimiento', models.DateField()),
                ('DNI', models.IntegerField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo números')])),
                ('Lejago', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo números')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número de teléfono válido')])),
                ('Curso', models.CharField(choices=[('Tm', 'Mañana'), ('Tt', 'Tarde'), ('Tn', 'Noche')], max_length=50)),
                ('Turno', models.CharField(max_length=25)),
                ('ServicioLocal', models.BooleanField()),
                ('ServicioLocalTexto', models.TextField()),
                ('Ausentismo', models.BooleanField()),
                ('AusentismoTexto', models.TextField()),
                ('DEI', models.BooleanField()),
                ('DEITexto', models.TextField()),
                ('Inclusion', models.BooleanField()),
                ('InclusionTexto', models.TextField()),
                ('Judicial', models.BooleanField()),
                ('JudicialTexto', models.TextField()),
                ('Conducta', models.BooleanField()),
                ('ConductaTexto', models.TextField()),
                ('actualizado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
