# Generated by Django 4.2.1 on 2023-05-10 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Curso',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='DNI',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo números')]),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Turno',
            field=models.CharField(choices=[('Tm', 'Mañana'), ('Tt', 'Tarde'), ('Tn', 'Noche')], max_length=50),
        ),
    ]
