# Generated by Django 4.2.1 on 2023-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro_alumnos', '0004_alter_alumnos_ausentismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Curso',
            field=models.CharField(choices=[('1ro 1ra', '1ro 1ra'), ('1ro 2da', '1ro 2da'), ('2do 1ra', '2do 1ra'), ('2do 2da', '2do 2da'), ('3ro 1ra', '3ro 1ra'), ('3ro 2da', '3ro 2da'), ('4to 1ra', '4to 1ra'), ('4to 2da', '4to 2da'), ('5to 1ra', '5to 1ra'), ('5to 2da', '5to 2da'), ('6to 1ra', '6to 1ra'), ('6to 2da', '6to 2da'), ('1ro 1ra', '1ro 1ra'), ('1ro 2da', '1ro 2da'), ('1ro 3ra', '1ro 3ra'), ('1ro 4ta', '1ro 4ta'), ('2do 1ra', '2do 1ra'), ('2do 2da', '2do 2da'), ('2do 3ra', '2do 3ra'), ('2do 4ta', '2do 4ta'), ('3ro 1ra', '3ro 1ra'), ('3ro 2da', '3ro 2da'), ('3ro 3ra', '3ro 3ra'), ('3to 4ta', '3ro 4ta'), ('4to ArLi', '4to ArLi'), ('4to Com', '4to Com'), ('5to ArLi', '5to ArLi'), ('5to Com', '5to Com'), ('6to ArLi', '6to ArLi'), ('6to Com', '6to Com')], max_length=25),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Escuela',
            field=models.CharField(choices=[('ES N°37', 'ES N°37'), ('ES N°46', 'ES N°46')], max_length=255),
        ),
    ]
